/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/_customer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStockBajoRouteImport } from './routes/admin/stock-bajo'
import { Route as AdminProductosRouteImport } from './routes/admin/productos'
import { Route as AdminCuponesRouteImport } from './routes/admin/cupones'
import { Route as AdminComprasRouteImport } from './routes/admin/compras'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as CustomerProductosRouteImport } from './routes/_customer/productos'
import { Route as CustomerComprasRouteImport } from './routes/_customer/compras'
import { Route as CustomerCheckoutRouteImport } from './routes/_customer/checkout'
import { Route as CustomerCarritoRouteImport } from './routes/_customer/carrito'
import { Route as AdminReportesTopProductosRouteImport } from './routes/admin/reportes.top-productos'
import { Route as AdminReportesFacturacionRouteImport } from './routes/admin/reportes.facturacion'
import { Route as CustomerProductosIdRouteImport } from './routes/_customer/productos.$id'
import { Route as CustomerComprasIdRouteImport } from './routes/_customer/compras.$id'
import { Route as AdminProductosIdVariantesRouteImport } from './routes/admin/productos.$id.variantes'
import { Route as CustomerComprasIdDevolucionRouteImport } from './routes/_customer/compras.$id.devolucion'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockBajoRoute = AdminStockBajoRouteImport.update({
  id: '/stock-bajo',
  path: '/stock-bajo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuponesRoute = AdminCuponesRouteImport.update({
  id: '/cupones',
  path: '/cupones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComprasRoute = AdminComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerProductosRoute = CustomerProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerComprasRoute = CustomerComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCarritoRoute = CustomerCarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminReportesTopProductosRoute =
  AdminReportesTopProductosRouteImport.update({
    id: '/reportes/top-productos',
    path: '/reportes/top-productos',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminReportesFacturacionRoute =
  AdminReportesFacturacionRouteImport.update({
    id: '/reportes/facturacion',
    path: '/reportes/facturacion',
    getParentRoute: () => AdminRoute,
  } as any)
const CustomerProductosIdRoute = CustomerProductosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerProductosRoute,
} as any)
const CustomerComprasIdRoute = CustomerComprasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerComprasRoute,
} as any)
const AdminProductosIdVariantesRoute =
  AdminProductosIdVariantesRouteImport.update({
    id: '/$id/variantes',
    path: '/$id/variantes',
    getParentRoute: () => AdminProductosRoute,
  } as any)
const CustomerComprasIdDevolucionRoute =
  CustomerComprasIdDevolucionRouteImport.update({
    id: '/devolucion',
    path: '/devolucion',
    getParentRoute: () => CustomerComprasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/carrito': typeof CustomerCarritoRoute
  '/checkout': typeof CustomerCheckoutRoute
  '/compras': typeof CustomerComprasRouteWithChildren
  '/productos': typeof CustomerProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/productos': typeof AdminProductosRouteWithChildren
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/': typeof AdminIndexRoute
  '/compras/$id': typeof CustomerComprasIdRouteWithChildren
  '/productos/$id': typeof CustomerProductosIdRoute
  '/admin/reportes/facturacion': typeof AdminReportesFacturacionRoute
  '/admin/reportes/top-productos': typeof AdminReportesTopProductosRoute
  '/compras/$id/devolucion': typeof CustomerComprasIdDevolucionRoute
  '/admin/productos/$id/variantes': typeof AdminProductosIdVariantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/carrito': typeof CustomerCarritoRoute
  '/checkout': typeof CustomerCheckoutRoute
  '/compras': typeof CustomerComprasRouteWithChildren
  '/productos': typeof CustomerProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/productos': typeof AdminProductosRouteWithChildren
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin': typeof AdminIndexRoute
  '/compras/$id': typeof CustomerComprasIdRouteWithChildren
  '/productos/$id': typeof CustomerProductosIdRoute
  '/admin/reportes/facturacion': typeof AdminReportesFacturacionRoute
  '/admin/reportes/top-productos': typeof AdminReportesTopProductosRoute
  '/compras/$id/devolucion': typeof CustomerComprasIdDevolucionRoute
  '/admin/productos/$id/variantes': typeof AdminProductosIdVariantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_customer': typeof CustomerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_customer/carrito': typeof CustomerCarritoRoute
  '/_customer/checkout': typeof CustomerCheckoutRoute
  '/_customer/compras': typeof CustomerComprasRouteWithChildren
  '/_customer/productos': typeof CustomerProductosRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/cupones': typeof AdminCuponesRoute
  '/admin/productos': typeof AdminProductosRouteWithChildren
  '/admin/stock-bajo': typeof AdminStockBajoRoute
  '/admin/': typeof AdminIndexRoute
  '/_customer/compras/$id': typeof CustomerComprasIdRouteWithChildren
  '/_customer/productos/$id': typeof CustomerProductosIdRoute
  '/admin/reportes/facturacion': typeof AdminReportesFacturacionRoute
  '/admin/reportes/top-productos': typeof AdminReportesTopProductosRoute
  '/_customer/compras/$id/devolucion': typeof CustomerComprasIdDevolucionRoute
  '/admin/productos/$id/variantes': typeof AdminProductosIdVariantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/carrito'
    | '/checkout'
    | '/compras'
    | '/productos'
    | '/admin/categorias'
    | '/admin/compras'
    | '/admin/cupones'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin/'
    | '/compras/$id'
    | '/productos/$id'
    | '/admin/reportes/facturacion'
    | '/admin/reportes/top-productos'
    | '/compras/$id/devolucion'
    | '/admin/productos/$id/variantes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/carrito'
    | '/checkout'
    | '/compras'
    | '/productos'
    | '/admin/categorias'
    | '/admin/compras'
    | '/admin/cupones'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin'
    | '/compras/$id'
    | '/productos/$id'
    | '/admin/reportes/facturacion'
    | '/admin/reportes/top-productos'
    | '/compras/$id/devolucion'
    | '/admin/productos/$id/variantes'
  id:
    | '__root__'
    | '/'
    | '/_customer'
    | '/admin'
    | '/login'
    | '/register'
    | '/_customer/carrito'
    | '/_customer/checkout'
    | '/_customer/compras'
    | '/_customer/productos'
    | '/admin/categorias'
    | '/admin/compras'
    | '/admin/cupones'
    | '/admin/productos'
    | '/admin/stock-bajo'
    | '/admin/'
    | '/_customer/compras/$id'
    | '/_customer/productos/$id'
    | '/admin/reportes/facturacion'
    | '/admin/reportes/top-productos'
    | '/_customer/compras/$id/devolucion'
    | '/admin/productos/$id/variantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-bajo': {
      id: '/admin/stock-bajo'
      path: '/stock-bajo'
      fullPath: '/admin/stock-bajo'
      preLoaderRoute: typeof AdminStockBajoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cupones': {
      id: '/admin/cupones'
      path: '/cupones'
      fullPath: '/admin/cupones'
      preLoaderRoute: typeof AdminCuponesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compras': {
      id: '/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AdminComprasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/productos': {
      id: '/_customer/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof CustomerProductosRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/compras': {
      id: '/_customer/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof CustomerComprasRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/checkout': {
      id: '/_customer/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/_customer/carrito': {
      id: '/_customer/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CustomerCarritoRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/reportes/top-productos': {
      id: '/admin/reportes/top-productos'
      path: '/reportes/top-productos'
      fullPath: '/admin/reportes/top-productos'
      preLoaderRoute: typeof AdminReportesTopProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes/facturacion': {
      id: '/admin/reportes/facturacion'
      path: '/reportes/facturacion'
      fullPath: '/admin/reportes/facturacion'
      preLoaderRoute: typeof AdminReportesFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_customer/productos/$id': {
      id: '/_customer/productos/$id'
      path: '/$id'
      fullPath: '/productos/$id'
      preLoaderRoute: typeof CustomerProductosIdRouteImport
      parentRoute: typeof CustomerProductosRoute
    }
    '/_customer/compras/$id': {
      id: '/_customer/compras/$id'
      path: '/$id'
      fullPath: '/compras/$id'
      preLoaderRoute: typeof CustomerComprasIdRouteImport
      parentRoute: typeof CustomerComprasRoute
    }
    '/admin/productos/$id/variantes': {
      id: '/admin/productos/$id/variantes'
      path: '/$id/variantes'
      fullPath: '/admin/productos/$id/variantes'
      preLoaderRoute: typeof AdminProductosIdVariantesRouteImport
      parentRoute: typeof AdminProductosRoute
    }
    '/_customer/compras/$id/devolucion': {
      id: '/_customer/compras/$id/devolucion'
      path: '/devolucion'
      fullPath: '/compras/$id/devolucion'
      preLoaderRoute: typeof CustomerComprasIdDevolucionRouteImport
      parentRoute: typeof CustomerComprasIdRoute
    }
  }
}

interface CustomerComprasIdRouteChildren {
  CustomerComprasIdDevolucionRoute: typeof CustomerComprasIdDevolucionRoute
}

const CustomerComprasIdRouteChildren: CustomerComprasIdRouteChildren = {
  CustomerComprasIdDevolucionRoute: CustomerComprasIdDevolucionRoute,
}

const CustomerComprasIdRouteWithChildren =
  CustomerComprasIdRoute._addFileChildren(CustomerComprasIdRouteChildren)

interface CustomerComprasRouteChildren {
  CustomerComprasIdRoute: typeof CustomerComprasIdRouteWithChildren
}

const CustomerComprasRouteChildren: CustomerComprasRouteChildren = {
  CustomerComprasIdRoute: CustomerComprasIdRouteWithChildren,
}

const CustomerComprasRouteWithChildren = CustomerComprasRoute._addFileChildren(
  CustomerComprasRouteChildren,
)

interface CustomerProductosRouteChildren {
  CustomerProductosIdRoute: typeof CustomerProductosIdRoute
}

const CustomerProductosRouteChildren: CustomerProductosRouteChildren = {
  CustomerProductosIdRoute: CustomerProductosIdRoute,
}

const CustomerProductosRouteWithChildren =
  CustomerProductosRoute._addFileChildren(CustomerProductosRouteChildren)

interface CustomerRouteChildren {
  CustomerCarritoRoute: typeof CustomerCarritoRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerComprasRoute: typeof CustomerComprasRouteWithChildren
  CustomerProductosRoute: typeof CustomerProductosRouteWithChildren
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerCarritoRoute: CustomerCarritoRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerComprasRoute: CustomerComprasRouteWithChildren,
  CustomerProductosRoute: CustomerProductosRouteWithChildren,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface AdminProductosRouteChildren {
  AdminProductosIdVariantesRoute: typeof AdminProductosIdVariantesRoute
}

const AdminProductosRouteChildren: AdminProductosRouteChildren = {
  AdminProductosIdVariantesRoute: AdminProductosIdVariantesRoute,
}

const AdminProductosRouteWithChildren = AdminProductosRoute._addFileChildren(
  AdminProductosRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminComprasRoute: typeof AdminComprasRoute
  AdminCuponesRoute: typeof AdminCuponesRoute
  AdminProductosRoute: typeof AdminProductosRouteWithChildren
  AdminStockBajoRoute: typeof AdminStockBajoRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportesFacturacionRoute: typeof AdminReportesFacturacionRoute
  AdminReportesTopProductosRoute: typeof AdminReportesTopProductosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminComprasRoute: AdminComprasRoute,
  AdminCuponesRoute: AdminCuponesRoute,
  AdminProductosRoute: AdminProductosRouteWithChildren,
  AdminStockBajoRoute: AdminStockBajoRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminReportesFacturacionRoute: AdminReportesFacturacionRoute,
  AdminReportesTopProductosRoute: AdminReportesTopProductosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
